const KEY='pitch-pocket-template-vault-v3',SETTINGS_KEY='pitch-pocket-profile-v1',ONBOARDING_KEY='pitch-pocket-onboarding-seen';
const starter=[
{id:'generic',emoji:'✨',name:'Generic',video:'',text:`Hi [brand]! 👋 I’d love to be considered. I create relatable, polished UGC designed to help brands build trust and make the product easy to understand.\n\n[portfolio] | [email]`},
{id:'fashion',emoji:'👗',name:'Fashion / Activewear',video:'',text:`Hi [brand]! 👋 I create fashion UGC that shows realistic fit, styling, movement, and how pieces actually wear in everyday life. I’d love to create for you!\n\n[portfolio] | [email]`},
{id:'beauty',emoji:'💄',name:'Beauty / Skincare',video:'',text:`Hi [brand]! 💕 I create clear, visually polished beauty content that highlights texture, application, routine, and the real product experience. I’d love to collaborate!\n\n[portfolio] | [email]`},
{id:'tech',emoji:'📱',name:'Apps / Tech / AI',video:'',text:`Hi [brand]! 👋 I create easy-to-follow tech UGC that shows how apps, software, websites, and AI tools solve real problems and fit naturally into daily life.\n\n[portfolio] | [email]`},
{id:'wellness',emoji:'🌿',name:'Wellness / Sports',video:'',text:`Hi [brand]! 👋 I create relatable wellness content around realistic routines, product education, and everyday use—without making it feel overly scripted or salesy.\n\n[portfolio] | [email]`},
{id:'food',emoji:'🍽️',name:'Kitchen / Food',video:'',text:`Hi [brand]! 🍽️ I create approachable food and kitchen content that makes products feel useful, craveable, and easy to picture in an everyday routine.\n\n[portfolio] | [email]`},
{id:'pet',emoji:'🐾',name:'Pet',video:'',text:`Hi [brand]! 🐾 I create playful, authentic pet UGC that shows products in real-life use and speaks naturally to the way pet parents shop and connect.\n\n[portfolio] | [email]`},
{id:'home',emoji:'🏡',name:'Home / Lifestyle',video:'',text:`Hi [brand]! 🏡 I create warm, relatable lifestyle content that shows how products fit into real homes, routines, and everyday moments. I’d love to create for you!\n\n[portfolio] | [email]`},
{id:'parenting',emoji:'🧸',name:'Parenting / Family',video:'',text:`Hi [brand]! 👋 I create honest, family-focused UGC that shows how products support real routines, solve everyday problems, and make life feel a little easier.\n\n[portfolio] | [email]`},
{id:'outdoor',emoji:'☀️',name:'Outdoor / Travel',video:'',text:`Hi [brand]! ☀️ I create energetic lifestyle UGC that shows products in motion, outdoors, and in real travel moments—not just sitting on a shelf.\n\n[portfolio] | [email]`}
];
let templates=load(),profile=loadProfile(),editingId=null,videoEnabled={};
const $=id=>document.getElementById(id);
function clone(v){return JSON.parse(JSON.stringify(v))}
function load(){try{const v=JSON.parse(localStorage.getItem(KEY));return Array.isArray(v)&&v.length?v:clone(starter)}catch{return clone(starter)}}
function save(){localStorage.setItem(KEY,JSON.stringify(templates))}
function loadProfile(){try{return Object.assign({name:'',portfolio:'',email:''},JSON.parse(localStorage.getItem(SETTINGS_KEY))||{})}catch{return{name:'',portfolio:'',email:''}}}
function saveProfileData(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(profile))}
function resolveTemplate(text){return text.replaceAll('[portfolio]',profile.portfolio||'https://yourportfolio.com').replaceAll('[email]',profile.email||'you@email.com').replaceAll('[name]',profile.name||'Your Name')}
function finalText(t){let text=resolveTemplate(t.text);if(videoEnabled[t.id]&&t.video)text+=`\nSample: ${t.video}`;return text}
function updateProfileStatus(){const ready=profile.portfolio&&profile.email;$('profileStatusTitle').textContent=ready?'Your pitches are ready to go ✨':'Set up your creator details';$('profileStatusText').textContent=ready?'Portfolio and email are automatically added to every copied pitch.':'Add your portfolio and email once so every pitch is ready to copy.';$('quickSetup').textContent=ready?'Edit →':'Set up →'}
function esc(s=''){return s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function countClass(n){return'count'+(n>280?' over':n>240?' warning':'')}
function render(){const box=$('vault');box.innerHTML='';templates.forEach(t=>{const resolved=finalText(t),card=document.createElement('article');card.className='card';card.innerHTML=`<div class="card-top"><div class="niche"><div class="emoji">${esc(t.emoji||'⭐')}</div><div><strong>${esc(t.name||'Untitled niche')}</strong><small>Saved niche pitch</small></div></div><span class="${countClass(resolved.length)}">${resolved.length} / 280</span></div><div class="pitch-preview">${esc(resolved)}</div>${t.video?`<div class="video-row"><div><label>Include matching sample</label><small>${videoEnabled[t.id]?'Added to copied pitch':'Saved and ready when relevant'}</small></div><label class="switch"><input type="checkbox" ${videoEnabled[t.id]?'checked':''}><span class="slider"></span></label></div>`:''}<div class="card-actions"><button class="copy-btn">▣ Copy ${esc(t.name||'Template')}</button><button class="edit-btn" aria-label="Edit ${esc(t.name||'template')}">✎</button></div>`;const toggle=card.querySelector('.switch input');if(toggle)toggle.onchange=e=>{videoEnabled[t.id]=e.target.checked;render()};card.querySelector('.copy-btn').onclick=()=>copy(finalText(t),`${t.name} pitch copied ✨`);card.querySelector('.edit-btn').onclick=()=>openEditor(t.id);box.appendChild(card)})}
function openEditor(id){editingId=id;const t=templates.find(x=>x.id===id);$('editorTitle').textContent=t?'Edit niche template':'Add niche template';$('nicheName').value=t?.name||'';$('nicheEmoji').value=t?.emoji||'⭐';$('templateText').value=t?.text||'Hi [brand]! 👋 ';$('videoLink').value=t?.video||'';$('builderIdentity').value='';$('builderCredibility').value='';$('builderBenefit').value='';$('builderStyle').selectedIndex=0;$('deleteTemplate').style.display=t?'block':'none';updateEditor();$('editorDialog').showModal()}
function updateEditor(){const resolved=resolveTemplate($('templateText').value),n=resolved.length;$('editorCount').textContent=`${n} / 280`;$('editorCount').className=countClass(n);$('editorPreview').textContent=resolved||'Your saved reply will preview here.'}
function compactPart(s,max){s=(s||'').trim().replace(/[.!]+$/,'');return s.length>max?s.slice(0,max-1).trim()+'…':s}
function buildPitch(){const identity=compactPart($('builderIdentity').value,42),credibility=compactPart($('builderCredibility').value,42),style=$('builderStyle').value,benefit=compactPart($('builderBenefit').value,52);if(!identity&&!credibility&&!benefit)return toast('Add at least one personal detail');const intro=[identity,credibility].filter(Boolean).join(' and ');let core=`Hi [brand]! 👋 ${intro?`I’m ${intro}. `:''}I create ${style}${benefit?` that show ${benefit}`:''}. I’d love to create for you!`;
const contact='\n\n[portfolio] | [email]';let candidate=core+contact;const resolvedLen=resolveTemplate(candidate).length;if(resolvedLen>280){core=`Hi [brand]! 👋 ${intro?`${intro} here. `:''}I create ${style}${benefit?` showing ${benefit}`:''}. Let’s create!`;candidate=core+contact}if(resolveTemplate(candidate).length>280){core=`Hi [brand]! 👋 I create ${style}${benefit?` showing ${compactPart(benefit,32)}`:''}. I’d love to create for you!`;candidate=core+contact}$('templateText').value=candidate;updateEditor();$('builderBudget').textContent=`${resolveTemplate(candidate).length} / 280 generated`;toast('Personalized pitch built ✨')}
function persistEditor(){const name=$('nicheName').value.trim()||'Untitled niche',emoji=$('nicheEmoji').value.trim()||'⭐',text=$('templateText').value.trim(),video=$('videoLink').value.trim();if(!text)return toast('Add your reply template first');if(editingId){Object.assign(templates.find(x=>x.id===editingId),{name,emoji,text,video})}else templates.push({id:'custom-'+Date.now(),name,emoji,text,video});save();render();$('editorDialog').close();toast('Template saved ✨')}
async function copy(text,message='Copied!'){try{await navigator.clipboard.writeText(text)}catch{const a=document.createElement('textarea');a.value=text;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove()}toast(message)}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1700)}
function showOnboarding(){const o=$('onboarding');o.style.display='block';o.scrollIntoView({behavior:'smooth',block:'start'})}
function dismissOnboarding(){localStorage.setItem(ONBOARDING_KEY,'1');$('onboarding').style.display='none'}
$('templateText').oninput=updateEditor;$('buildPitch').onclick=buildPitch;$('saveTemplate').onclick=persistEditor;$('copyFromEditor').onclick=()=>copy(resolveTemplate($('templateText').value),'Template copied ✨');$('deleteTemplate').onclick=()=>{if(!editingId)return;templates=templates.filter(x=>x.id!==editingId);save();render();$('editorDialog').close();toast('Template deleted')};$('closeEditor').onclick=()=>$('editorDialog').close();$('addTemplate').onclick=()=>openEditor(null);$('settingsAdd').onclick=()=>{$('settingsDialog').close();openEditor(null)};
function openSettings(){profile=loadProfile();$('profileName').value=profile.name||'';$('profilePortfolio').value=profile.portfolio||'';$('profileEmail').value=profile.email||'';$('settingsDialog').showModal()}
$('openSettings').onclick=openSettings;$('quickSetup').onclick=openSettings;$('onboardingSetup').onclick=()=>{dismissOnboarding();openSettings()};$('onboardingDone').onclick=dismissOnboarding;$('dismissOnboarding').onclick=dismissOnboarding;$('showOnboarding').onclick=()=>{$('settingsDialog').close();localStorage.removeItem(ONBOARDING_KEY);showOnboarding()};$('closeSettings').onclick=()=>$('settingsDialog').close();$('saveProfile').onclick=()=>{profile={name:$('profileName').value.trim(),portfolio:$('profilePortfolio').value.trim(),email:$('profileEmail').value.trim()};if(!profile.portfolio||!profile.email)return toast('Add both your portfolio and email');saveProfileData();render();updateProfileStatus();$('settingsDialog').close();toast('Creator details saved ✨')};$('restoreDefaults').onclick=()=>{templates=clone(starter);save();render();$('settingsDialog').close();toast('Starter templates restored')};[$('editorDialog'),$('settingsDialog')].forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}));
if(localStorage.getItem(ONBOARDING_KEY)==='1')$('onboarding').style.display='none';render();updateProfileStatus();